### PR TITLE
Markdown fixes

### PR DESCRIPTION
**Pull request by honza**
Most of the images in the `1-deployment` directory don't render properly. This is because your image files have spaces in them, and GitHub doesn't know what to do with that. Once solution is to replace spaces in filenames with `%20` but that's dumb. Instead, I renamed the image files: I replaced the spaces with dashes. Then I updated the references to the new filenames in the markdown file. On top of all of that, I renamed the markdown file to `README.md` which will cause GitHub to render it on the directory listing page, saving us all a click.

If you like this approach, I can update the other directories as well (I'll update this PR).

### CODE REVIEW

**Comment by lizsurette** [comment]
@honza Thanks for finding this issue and fixing! This works fine for me, I can rename my file so that the output images follow this naming scheme too. Feel free to rename the others in other directories if you would like :)

**Comment by honza** [comment]
I just realized that the primary presentation location is the rendered website, and not the GitHub UI. So, this is probably unnecessary.

**Comment by lizsurette** [comment]
@honza Well I guess it depends on how people will review things, too. It probably can't hurt to make sure these images work on the GitHub UI, too right?

**Review by lizsurette — APPROVED** [review]
Thanks for this! I'm updating a few other items so I will make the naming changes to the other 2 directories now :)

**Comment by lizsurette** [comment]
@honza I committed these to fix the other directories... 
https://github.com/lizsurette/OpenStack-Design/commit/2eb34c41591bcd742f41b3b6e27d4011dfaa2f83
https://github.com/lizsurette/OpenStack-Design/commit/244e952e38e352f7f22cd256330182649e84d1a9

**Pull request merged**
